/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.progavud.parcial2pa.vista;

import edu.progavud.parcial2pa.control.ControlVentanaServidor;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import javax.accessibility.AccessibleContext;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;

/**
 * Ventana principal de la interfaz gráfica del servidor.
 * Esta clase gestiona la interfaz que permite visualizar los botones de cartas, 
 * controlar el flujo de la partida y mostrar mensajes del servidor.
 * Forma parte de la arquitectura MVC como la "Vista" del servidor.
 * 
 * Dispone de una matriz de botones que representan las cartas, y otra matriz para
 * almacenar los índices asociados a cada carta. También mantiene una referencia
 * al controlador que gestiona los eventos de esta vista.
 * 
 * Utiliza el logger para registrar eventos relevantes de la aplicación.
 * 
 * @author hailen
 */
public class VistaServidor extends javax.swing.JFrame {

     /**
     * Controlador asociado a esta vista, maneja la lógica de eventos.
     */
    private ControlVentanaServidor cVentanaServidor;

    /**
     * Matriz de botones que representan las cartas en el tablero.
     * Tiene 5 filas y 8 columnas (40 botones en total).
     */
    private JButton[][] botones = new JButton[5][8];

    /**
     * Matriz de índices asociada a cada botón de carta. Se usa para 
     * identificar las cartas emparejadas o destapadas.
     */
    private int[][] indiceBotones = new int[5][8];

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaServidor.class.getName());

    /**
     * Creates new form VistaServidor
     */
    public VistaServidor() {
        super("VISTA-SERVIDOR");
        this.cVentanaServidor = cVentanaServidor;
        initComponents();
        ponerBotonesEnMatriz();
        setearIMGs();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCarta2 = new javax.swing.JButton();
        btnCarta1 = new javax.swing.JButton();
        btnCarta3 = new javax.swing.JButton();
        btnCarta4 = new javax.swing.JButton();
        btnCarta5 = new javax.swing.JButton();
        btnCarta6 = new javax.swing.JButton();
        btnCarta7 = new javax.swing.JButton();
        btnCarta8 = new javax.swing.JButton();
        btnCarta9 = new javax.swing.JButton();
        btnCarta17 = new javax.swing.JButton();
        btnCarta25 = new javax.swing.JButton();
        btnCarta33 = new javax.swing.JButton();
        btnCarta10 = new javax.swing.JButton();
        btnCarta18 = new javax.swing.JButton();
        btnCarta26 = new javax.swing.JButton();
        btnCarta34 = new javax.swing.JButton();
        btnCarta11 = new javax.swing.JButton();
        btnCarta19 = new javax.swing.JButton();
        btnCarta27 = new javax.swing.JButton();
        btnCarta35 = new javax.swing.JButton();
        btnCarta12 = new javax.swing.JButton();
        btnCarta20 = new javax.swing.JButton();
        btnCarta28 = new javax.swing.JButton();
        btnCarta36 = new javax.swing.JButton();
        btnCarta13 = new javax.swing.JButton();
        btnCarta21 = new javax.swing.JButton();
        btnCarta29 = new javax.swing.JButton();
        btnCarta37 = new javax.swing.JButton();
        btnCarta14 = new javax.swing.JButton();
        btnCarta22 = new javax.swing.JButton();
        btnCarta30 = new javax.swing.JButton();
        btnCarta38 = new javax.swing.JButton();
        btnCarta15 = new javax.swing.JButton();
        btnCarta23 = new javax.swing.JButton();
        btnCarta31 = new javax.swing.JButton();
        btnCarta39 = new javax.swing.JButton();
        btnCarta16 = new javax.swing.JButton();
        btnCarta24 = new javax.swing.JButton();
        btnCarta32 = new javax.swing.JButton();
        btnCarta40 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMostrar = new javax.swing.JTextArea();
        lblAciertosJug1 = new javax.swing.JLabel();
        lblIntentosJug1 = new javax.swing.JLabel();
        btnJug1 = new javax.swing.JButton();
        lblAciertosJug2 = new javax.swing.JLabel();
        lblIntentosJug2 = new javax.swing.JLabel();
        btnJug2 = new javax.swing.JButton();
        lblAciertosJug3 = new javax.swing.JLabel();
        lblIntentosJug3 = new javax.swing.JLabel();
        btnJug3 = new javax.swing.JButton();
        lblAciertosJug4 = new javax.swing.JLabel();
        lblIntentosJug4 = new javax.swing.JLabel();
        btnJug4 = new javax.swing.JButton();
        btnEnviarResultados = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAumentarIntento = new javax.swing.JButton();
        btnIniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnCarta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N
        btnCarta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta3ActionPerformed(evt);
            }
        });

        btnCarta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N
        btnCarta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta4ActionPerformed(evt);
            }
        });

        btnCarta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N
        btnCarta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta6ActionPerformed(evt);
            }
        });

        btnCarta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N
        btnCarta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta9ActionPerformed(evt);
            }
        });

        btnCarta17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N
        btnCarta26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta26ActionPerformed(evt);
            }
        });

        btnCarta34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N
        btnCarta35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta35ActionPerformed(evt);
            }
        });

        btnCarta12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N
        btnCarta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta13ActionPerformed(evt);
            }
        });

        btnCarta21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        btnCarta32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N
        btnCarta32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta32ActionPerformed(evt);
            }
        });

        btnCarta40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg"))); // NOI18N

        txaMostrar.setEditable(false);
        txaMostrar.setBackground(new java.awt.Color(102, 102, 102));
        txaMostrar.setColumns(20);
        txaMostrar.setForeground(new java.awt.Color(255, 255, 255));
        txaMostrar.setRows(5);
        jScrollPane1.setViewportView(txaMostrar);

        lblAciertosJug1.setForeground(new java.awt.Color(255, 255, 255));
        lblAciertosJug1.setText("Aciertos: 0");

        lblIntentosJug1.setForeground(new java.awt.Color(255, 255, 255));
        lblIntentosJug1.setText("Intentos: 0");

        btnJug1.setBackground(new java.awt.Color(102, 102, 102));
        btnJug1.setForeground(new java.awt.Color(255, 255, 255));
        btnJug1.setText("Pedir coords Jug 1");

        lblAciertosJug2.setForeground(new java.awt.Color(255, 255, 255));
        lblAciertosJug2.setText("Aciertos: 0");

        lblIntentosJug2.setForeground(new java.awt.Color(255, 255, 255));
        lblIntentosJug2.setText("Intentos: 0");

        btnJug2.setBackground(new java.awt.Color(102, 102, 102));
        btnJug2.setForeground(new java.awt.Color(255, 255, 255));
        btnJug2.setText("Pedir coords Jug 2");
        btnJug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJug2ActionPerformed(evt);
            }
        });

        lblAciertosJug3.setForeground(new java.awt.Color(255, 255, 255));
        lblAciertosJug3.setText("Aciertos: 0");

        lblIntentosJug3.setForeground(new java.awt.Color(255, 255, 255));
        lblIntentosJug3.setText("Intentos: 0");

        btnJug3.setBackground(new java.awt.Color(102, 102, 102));
        btnJug3.setForeground(new java.awt.Color(255, 255, 255));
        btnJug3.setText("Pedir coords Jug 3");

        lblAciertosJug4.setForeground(new java.awt.Color(255, 255, 255));
        lblAciertosJug4.setText("Aciertos: 0");

        lblIntentosJug4.setForeground(new java.awt.Color(255, 255, 255));
        lblIntentosJug4.setText("Intentos: 0");

        btnJug4.setBackground(new java.awt.Color(102, 102, 102));
        btnJug4.setForeground(new java.awt.Color(255, 255, 255));
        btnJug4.setText("Pedir coords Jug 4");

        btnEnviarResultados.setBackground(new java.awt.Color(102, 102, 102));
        btnEnviarResultados.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarResultados.setText("Enviar Resultados");

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        btnAumentarIntento.setBackground(new java.awt.Color(102, 102, 102));
        btnAumentarIntento.setForeground(new java.awt.Color(255, 255, 255));
        btnAumentarIntento.setText("Intento +1 (mensaje invalido)");

        btnIniciarJuego.setBackground(new java.awt.Color(102, 102, 102));
        btnIniciarJuego.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarJuego.setText("Iniciar Juego");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCarta25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCarta17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCarta9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCarta33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCarta34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblAciertosJug1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addComponent(lblIntentosJug1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCarta35, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCarta36, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblAciertosJug2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblIntentosJug2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnJug1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btnJug2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCarta37, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCarta38, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnJug3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblIntentosJug3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAciertosJug3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJug4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCarta39, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCarta40, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblIntentosJug4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAciertosJug4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIniciarJuego)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAumentarIntento)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEnviarResultados)
                                .addGap(98, 98, 98))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarta9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarta17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarta25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarta33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta35, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta36, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta37, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta38, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta39, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarta40, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAciertosJug1)
                            .addComponent(lblAciertosJug2)
                            .addComponent(lblAciertosJug3)
                            .addComponent(lblAciertosJug4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIntentosJug1)
                            .addComponent(lblIntentosJug2)
                            .addComponent(lblIntentosJug3)
                            .addComponent(lblIntentosJug4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnJug1)
                            .addComponent(btnJug2)
                            .addComponent(btnJug3)
                            .addComponent(btnJug4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIniciarJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAumentarIntento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviarResultados)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarta4ActionPerformed

    private void btnCarta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarta6ActionPerformed

    private void btnJug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJug2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJug2ActionPerformed

    private void btnCarta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarta3ActionPerformed

    private void btnCarta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarta9ActionPerformed

    private void btnCarta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarta13ActionPerformed

    private void btnCarta26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarta26ActionPerformed

    private void btnCarta32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarta32ActionPerformed

    private void btnCarta35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarta35ActionPerformed

    /**
     * @param args the command line arguments
     */


    public JButton getBtnCarta1() {
        return btnCarta1;
    }

    public void setBtnCarta1(JButton btnCarta1) {
        this.btnCarta1 = btnCarta1;
    }

    public JButton getBtnCarta10() {
        return btnCarta10;
    }

    public void setBtnCarta10(JButton btnCarta10) {
        this.btnCarta10 = btnCarta10;
    }

    public JButton getBtnCarta11() {
        return btnCarta11;
    }

    public void setBtnCarta11(JButton btnCarta11) {
        this.btnCarta11 = btnCarta11;
    }

    public JButton getBtnCarta12() {
        return btnCarta12;
    }

    public void setBtnCarta12(JButton btnCarta12) {
        this.btnCarta12 = btnCarta12;
    }

    public JButton getBtnCarta13() {
        return btnCarta13;
    }

    public void setBtnCarta13(JButton btnCarta13) {
        this.btnCarta13 = btnCarta13;
    }

    public JButton getBtnCarta14() {
        return btnCarta14;
    }

    public void setBtnCarta14(JButton btnCarta14) {
        this.btnCarta14 = btnCarta14;
    }

    public JButton getBtnCarta15() {
        return btnCarta15;
    }

    public void setBtnCarta15(JButton btnCarta15) {
        this.btnCarta15 = btnCarta15;
    }

    public JButton getBtnCarta16() {
        return btnCarta16;
    }

    public void setBtnCarta16(JButton btnCarta16) {
        this.btnCarta16 = btnCarta16;
    }

    public JButton getBtnCarta17() {
        return btnCarta17;
    }

    public void setBtnCarta17(JButton btnCarta17) {
        this.btnCarta17 = btnCarta17;
    }

    public JButton getBtnCarta18() {
        return btnCarta18;
    }

    public void setBtnCarta18(JButton btnCarta18) {
        this.btnCarta18 = btnCarta18;
    }

    public JButton getBtnCarta19() {
        return btnCarta19;
    }

    public void setBtnCarta19(JButton btnCarta19) {
        this.btnCarta19 = btnCarta19;
    }

    public JButton getBtnCarta2() {
        return btnCarta2;
    }

    public void setBtnCarta2(JButton btnCarta2) {
        this.btnCarta2 = btnCarta2;
    }

    public JButton getBtnCarta20() {
        return btnCarta20;
    }

    public void setBtnCarta20(JButton btnCarta20) {
        this.btnCarta20 = btnCarta20;
    }

    public JButton getBtnCarta21() {
        return btnCarta21;
    }

    public void setBtnCarta21(JButton btnCarta21) {
        this.btnCarta21 = btnCarta21;
    }

    public JButton getBtnCarta22() {
        return btnCarta22;
    }

    public void setBtnCarta22(JButton btnCarta22) {
        this.btnCarta22 = btnCarta22;
    }

    public JButton getBtnCarta23() {
        return btnCarta23;
    }

    public void setBtnCarta23(JButton btnCarta23) {
        this.btnCarta23 = btnCarta23;
    }

    public JButton getBtnCarta24() {
        return btnCarta24;
    }

    public void setBtnCarta24(JButton btnCarta24) {
        this.btnCarta24 = btnCarta24;
    }

    public JButton getBtnCarta25() {
        return btnCarta25;
    }

    public void setBtnCarta25(JButton btnCarta25) {
        this.btnCarta25 = btnCarta25;
    }

    public JButton getBtnCarta26() {
        return btnCarta26;
    }

    public void setBtnCarta26(JButton btnCarta26) {
        this.btnCarta26 = btnCarta26;
    }

    public JButton getBtnCarta27() {
        return btnCarta27;
    }

    public void setBtnCarta27(JButton btnCarta27) {
        this.btnCarta27 = btnCarta27;
    }

    public JButton getBtnCarta28() {
        return btnCarta28;
    }

    public void setBtnCarta28(JButton btnCarta28) {
        this.btnCarta28 = btnCarta28;
    }

    public JButton getBtnCarta29() {
        return btnCarta29;
    }

    public void setBtnCarta29(JButton btnCarta29) {
        this.btnCarta29 = btnCarta29;
    }

    public JButton getBtnCarta3() {
        return btnCarta3;
    }

    public void setBtnCarta3(JButton btnCarta3) {
        this.btnCarta3 = btnCarta3;
    }

    public JButton getBtnCarta30() {
        return btnCarta30;
    }

    public void setBtnCarta30(JButton btnCarta30) {
        this.btnCarta30 = btnCarta30;
    }

    public JButton getBtnCarta31() {
        return btnCarta31;
    }

    public void setBtnCarta31(JButton btnCarta31) {
        this.btnCarta31 = btnCarta31;
    }

    public JButton getBtnCarta32() {
        return btnCarta32;
    }

    public void setBtnCarta32(JButton btnCarta32) {
        this.btnCarta32 = btnCarta32;
    }

    public JButton getBtnCarta33() {
        return btnCarta33;
    }

    public void setBtnCarta33(JButton btnCarta33) {
        this.btnCarta33 = btnCarta33;
    }

    public JButton getBtnCarta34() {
        return btnCarta34;
    }

    public void setBtnCarta34(JButton btnCarta34) {
        this.btnCarta34 = btnCarta34;
    }

    public JButton getBtnCarta35() {
        return btnCarta35;
    }

    public void setBtnCarta35(JButton btnCarta35) {
        this.btnCarta35 = btnCarta35;
    }

    public JButton getBtnCarta36() {
        return btnCarta36;
    }

    public void setBtnCarta36(JButton btnCarta36) {
        this.btnCarta36 = btnCarta36;
    }

    public JButton getBtnCarta37() {
        return btnCarta37;
    }

    public void setBtnCarta37(JButton btnCarta37) {
        this.btnCarta37 = btnCarta37;
    }

    public JButton getBtnCarta38() {
        return btnCarta38;
    }

    public void setBtnCarta38(JButton btnCarta38) {
        this.btnCarta38 = btnCarta38;
    }

    public JButton getBtnCarta39() {
        return btnCarta39;
    }

    public void setBtnCarta39(JButton btnCarta39) {
        this.btnCarta39 = btnCarta39;
    }

    public JButton getBtnCarta4() {
        return btnCarta4;
    }

    public void setBtnCarta4(JButton btnCarta4) {
        this.btnCarta4 = btnCarta4;
    }

    public JButton getBtnCarta40() {
        return btnCarta40;
    }

    public void setBtnCarta40(JButton btnCarta40) {
        this.btnCarta40 = btnCarta40;
    }

    public JButton getBtnCarta5() {
        return btnCarta5;
    }

    public void setBtnCarta5(JButton btnCarta5) {
        this.btnCarta5 = btnCarta5;
    }

    public JButton getBtnCarta6() {
        return btnCarta6;
    }

    public void setBtnCarta6(JButton btnCarta6) {
        this.btnCarta6 = btnCarta6;
    }

    public JButton getBtnCarta7() {
        return btnCarta7;
    }

    public void setBtnCarta7(JButton btnCarta7) {
        this.btnCarta7 = btnCarta7;
    }

    public JButton getBtnCarta8() {
        return btnCarta8;
    }

    public void setBtnCarta8(JButton btnCarta8) {
        this.btnCarta8 = btnCarta8;
    }

    public JButton getBtnCarta9() {
        return btnCarta9;
    }

    public void setBtnCarta9(JButton btnCarta9) {
        this.btnCarta9 = btnCarta9;
    }

    public JButton getBtnEnviarResultados() {
        return btnEnviarResultados;
    }

    public void setBtnEnviarResultados(JButton btnEnviarResultados) {
        this.btnEnviarResultados = btnEnviarResultados;
    }

    public JButton getBtnJug1() {
        return btnJug1;
    }

    public void setBtnJug1(JButton btnJug1) {
        this.btnJug1 = btnJug1;
    }

    public JButton getBtnJug2() {
        return btnJug2;
    }

    public void setBtnJug2(JButton btnJug2) {
        this.btnJug2 = btnJug2;
    }

    public JButton getBtnJug3() {
        return btnJug3;
    }

    public void setBtnJug3(JButton btnJug3) {
        this.btnJug3 = btnJug3;
    }

    public JButton getBtnJug4() {
        return btnJug4;
    }

    public void setBtnJug4(JButton btnJug4) {
        this.btnJug4 = btnJug4;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getLblAciertosJug1() {
        return lblAciertosJug1;
    }

    public void setLblAciertosJug1(JLabel lblAciertosJug1) {
        this.lblAciertosJug1 = lblAciertosJug1;
    }

    public JLabel getLblAciertosJug2() {
        return lblAciertosJug2;
    }

    public void setLblAciertosJug2(JLabel lblAciertosJug2) {
        this.lblAciertosJug2 = lblAciertosJug2;
    }

    public JLabel getLblAciertosJug3() {
        return lblAciertosJug3;
    }

    public void setLblAciertosJug3(JLabel lblAciertosJug3) {
        this.lblAciertosJug3 = lblAciertosJug3;
    }

    public JLabel getLblAciertosJug4() {
        return lblAciertosJug4;
    }

    public void setLblAciertosJug4(JLabel lblAciertosJug4) {
        this.lblAciertosJug4 = lblAciertosJug4;
    }

    public JLabel getLblIntentosJug1() {
        return lblIntentosJug1;
    }

    public void setLblIntentosJug1(JLabel lblIntentosJug1) {
        this.lblIntentosJug1 = lblIntentosJug1;
    }

    public JLabel getLblIntentosJug2() {
        return lblIntentosJug2;
    }

    public void setLblIntentosJug2(JLabel lblIntentosJug2) {
        this.lblIntentosJug2 = lblIntentosJug2;
    }

    public JLabel getLblIntentosJug3() {
        return lblIntentosJug3;
    }

    public void setLblIntentosJug3(JLabel lblIntentosJug3) {
        this.lblIntentosJug3 = lblIntentosJug3;
    }

    public JLabel getLblIntentosJug4() {
        return lblIntentosJug4;
    }

    public void setLblIntentosJug4(JLabel lblIntentosJug4) {
        this.lblIntentosJug4 = lblIntentosJug4;
    }

    public JTextArea getTxaMostrar() {
        return txaMostrar;
    }

    /**
     * Retorna el área de texto usada para mostrar mensajes en la ventana del
     * servidor.
     *
     * @return JTextArea que contiene los mensajes del servidor.
     */
    public void setTxaMostrar(JTextArea txaMostrar) {
        this.txaMostrar = txaMostrar;
    }

    /**
     * Agrega un mensaje al área de texto del servidor, mostrándolo en pantalla.
     *
     * @param msg El mensaje a mostrar.
     */
    public void mostrar(String msg) {
        txaMostrar.append(msg + "\n");
    }

    private void ponerBotonesEnMatriz() {

//        JButton[] btnCartas = {
//            btnCarta1, btnCarta2, btnCarta3, btnCarta4, btnCarta5, btnCarta6, btnCarta7, btnCarta8,
//            btnCarta9, btnCarta10, btnCarta11, btnCarta12, btnCarta13, btnCarta14, btnCarta15, btnCarta16,
//            btnCarta17, btnCarta18, btnCarta19, btnCarta20, btnCarta21, btnCarta22, btnCarta23, btnCarta24,
//            btnCarta25, btnCarta26, btnCarta27, btnCarta28, btnCarta29, btnCarta30, btnCarta31, btnCarta32,
//            btnCarta33, btnCarta34, btnCarta35, btnCarta36, btnCarta37, btnCarta38, btnCarta39, btnCarta40
//        };
        int numero = 1;
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 8; j++) {
                indiceBotones[i][j] = numero;
                numero++;
            }
        }
    }

    public ImageIcon cargarCarta(String ruta) {
        URL url = getClass().getResource(ruta);

//        if (url != null) {
        // Cargar imagen original
        ImageIcon iconOriginal = new ImageIcon(url);

        // Redimensionar a 140x140
        // Crear nuevo icono con la imagen redimensionada
        ImageIcon iconRedimensionado = new ImageIcon(iconOriginal.getImage());

        // Asignar al JLabel
//        } else {
//            System.out.println("No se encontró la imagen: /imgGatos/" + nombreImagen);
//        }
        return iconRedimensionado;
    }

    public JButton[][] getBotones() {
        return botones;
    }

    public void setBotones(JButton[][] botones) {
        this.botones = botones;
    }

    public void mostrarJDialogParejaEncontrada() {
        JOptionPane.showMessageDialog(null, "¡Pareja encontrada!");
    }

    public void setearIMGs() {
        btnCarta1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta13.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta14.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta15.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta16.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta17.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta18.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta19.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta20.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta21.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta22.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta23.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta24.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta25.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta26.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta27.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta28.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta29.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta30.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta31.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta32.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta33.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta34.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta35.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta36.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta37.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta38.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta39.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));
        btnCarta40.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/cn.jpg")));

    }

    public JButton getBtnAumentarIntento() {
        return btnAumentarIntento;
    }

    public void setBtnAumentarIntento(JButton btnAumentarIntento) {
        this.btnAumentarIntento = btnAumentarIntento;
    }

    public JButton getBtnIniciarJuego() {
        return btnIniciarJuego;
    }

    public void setBtnIniciarJuego(JButton btnIniciarJuego) {
        this.btnIniciarJuego = btnIniciarJuego;
    }

    public int[][] getIndiceBotones() {
        return indiceBotones;
    }

    public void setIndiceBotones(int[][] indiceBotones) {
        this.indiceBotones = indiceBotones;
    }

    public File rutaJfileChooserPorts() {
        File f;
        JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
        fc.showDialog(null, "Seleccionar Archivo Properties de los Ports");

        f = fc.getSelectedFile();
        return f;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAumentarIntento;
    private javax.swing.JButton btnCarta1;
    private javax.swing.JButton btnCarta10;
    private javax.swing.JButton btnCarta11;
    private javax.swing.JButton btnCarta12;
    private javax.swing.JButton btnCarta13;
    private javax.swing.JButton btnCarta14;
    private javax.swing.JButton btnCarta15;
    private javax.swing.JButton btnCarta16;
    private javax.swing.JButton btnCarta17;
    private javax.swing.JButton btnCarta18;
    private javax.swing.JButton btnCarta19;
    private javax.swing.JButton btnCarta2;
    private javax.swing.JButton btnCarta20;
    private javax.swing.JButton btnCarta21;
    private javax.swing.JButton btnCarta22;
    private javax.swing.JButton btnCarta23;
    private javax.swing.JButton btnCarta24;
    private javax.swing.JButton btnCarta25;
    private javax.swing.JButton btnCarta26;
    private javax.swing.JButton btnCarta27;
    private javax.swing.JButton btnCarta28;
    private javax.swing.JButton btnCarta29;
    private javax.swing.JButton btnCarta3;
    private javax.swing.JButton btnCarta30;
    private javax.swing.JButton btnCarta31;
    private javax.swing.JButton btnCarta32;
    private javax.swing.JButton btnCarta33;
    private javax.swing.JButton btnCarta34;
    private javax.swing.JButton btnCarta35;
    private javax.swing.JButton btnCarta36;
    private javax.swing.JButton btnCarta37;
    private javax.swing.JButton btnCarta38;
    private javax.swing.JButton btnCarta39;
    private javax.swing.JButton btnCarta4;
    private javax.swing.JButton btnCarta40;
    private javax.swing.JButton btnCarta5;
    private javax.swing.JButton btnCarta6;
    private javax.swing.JButton btnCarta7;
    private javax.swing.JButton btnCarta8;
    private javax.swing.JButton btnCarta9;
    private javax.swing.JButton btnEnviarResultados;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JButton btnJug1;
    private javax.swing.JButton btnJug2;
    private javax.swing.JButton btnJug3;
    private javax.swing.JButton btnJug4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAciertosJug1;
    private javax.swing.JLabel lblAciertosJug2;
    private javax.swing.JLabel lblAciertosJug3;
    private javax.swing.JLabel lblAciertosJug4;
    private javax.swing.JLabel lblIntentosJug1;
    private javax.swing.JLabel lblIntentosJug2;
    private javax.swing.JLabel lblIntentosJug3;
    private javax.swing.JLabel lblIntentosJug4;
    private javax.swing.JTextArea txaMostrar;
    // End of variables declaration//GEN-END:variables
}
